---
title: "Plotly"
output:
  html_document:
    toc: true
    toc_float: true
---

# This is about plot


```{r}
Sys.setlocale("LC_TIME", "C")
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(rnoaa)
library(lubridate)
```


```{r}
noaa <- read_csv("data/nynoaadat.csv")

clean_noaa <- noaa %>%
  mutate(
    precip = case_when(
      prcp == 0 ~ "No Precipitation",
      prcp > 0 & prcp <= 10 ~ "Light",
      prcp > 10 & prcp <= 30 ~ "Moderate",
      prcp > 30 ~ "Heavy"
    )
  ) %>%
  select(id, date, tmax, tmin, prcp, precip) %>%
  filter(
    !is.na(tmax),
    !is.na(prcp),
    precip %in% c("Light", "Moderate", "Heavy")
  )

head(clean_noaa)
```


```{r}
set.seed(888)  
sample <- clean_noaa %>% sample_n(5000)
```

```{r}
#scatter plot of maximum temperature over time
plot1 <- plot_ly(sample, x = ~date, y = ~tmax, type = 'scatter', mode = 'markers') %>%
  layout(title = "Maximum Temperature Over Time",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Max Temperature"))
plot1
```


```{r}
#compute the average maximum temperature
avg_temp <- sample %>%
  group_by(precip) %>%
  summarize(avg_tmax = mean(tmax, na.rm = TRUE))

#bar plot
plot2 <- plot_ly(avg_temp, x = ~precip, y = ~avg_tmax, type = 'bar') %>%
  layout(title = "Average Maximum Temperature by Precipitation Intensity",
         xaxis = list(title = "Precipitation Intensity"),
         yaxis = list(title = "Average Max Temperature"))
plot2
```


```{r}
#make a new column for data by month
sample <- sample %>%
  mutate(month = month(date, label = TRUE))

#box plot for temperature distribution by month
plot3 <- plot_ly(sample, x = ~month, y = ~tmax, type = 'box') %>%
  layout(title = "Temperature Distribution by Month",
         xaxis = list(title = "Month"),
         yaxis = list(title = "Max Temperature"))
plot3
```

